name: setup-devbox |
  action for setup of devbox and pnpm

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install devbox
      uses: jetify-com/devbox-install-action@v0.11.0
      with:
          enable-cache: 'true'