name: _install_pnpm_deps

on:
  workflow_call:

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Devbox
        uses: ./.github/actions/setup_devbox

      - name: Install Dependencies
        run: devbox run pnpm install --frozen-lockfile