name: _verify

on:
  workflow_call:

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2

      - name: Run Biome
        run: biome ci .

  test:
    name: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Devbox
        uses: ./.github/actions/setup_devbox

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Tests
        run: pnpm test:coverage

      - name: Report Coverage
        if: always() 
        uses:  davelosert/vitest-coverage-report-action@v2
        with:
          file-coverage-mode: all